package GUI;

import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import main.GamePanel;

public class ReportView {
    GamePanel gp;
    public Rectangle backBtn;

    public ReportView(GamePanel gp) {
        this.gp = gp;
        backBtn = new Rectangle(gp.screenWidth / 2 - 60, gp.screenHeight - 80, 120, 40);
    }

    public void draw(Graphics2D g2) {
        // 1. Background (Light Grey)
        g2.setColor(new Color(245, 245, 245));
        g2.fillRect(0, 0, gp.screenWidth, gp.screenHeight);

        // 2. Title
        g2.setFont(new Font("Arial", Font.BOLD, 26));
        g2.setColor(new Color(50, 50, 50));
        g2.drawString("Official Term Performance Report", 100, 70);
        
        // Draw a decorative line under the title
        g2.setStroke(new BasicStroke(2));
        g2.drawLine(100, 85, gp.screenWidth - 100, 85);

        // 3. Content Area
        g2.setFont(new Font("Consolas", Font.PLAIN, 16)); // Consolas looks better for reports
        g2.setColor(Color.BLACK);
        
        int yStart = 140;
        int lineSpacing = 30;

        // We only need to read the final report generated by ReportManager
        try (BufferedReader reader = new BufferedReader(new FileReader("res/report.txt"))) {
            String line;
            int currentY = yStart;
            while ((line = reader.readLine()) != null) {
                g2.drawString(line, 120, currentY);
                currentY += lineSpacing;
            }
        } catch (IOException e) {
            g2.setFont(new Font("Arial", Font.ITALIC, 16));
            g2.setColor(Color.GRAY);
            g2.drawString("The term is currently in progress...", 120, 200);
            g2.drawString("The final report will be generated automatically upon completion.", 120, 230);
        }

      
        drawBackButton(g2);
    }

    private void drawBackButton(Graphics2D g2) {
        g2.setColor(new Color(255, 215, 0)); // Gold
        g2.fill(backBtn);
        g2.setColor(Color.BLACK);
        g2.setStroke(new BasicStroke(1));
        g2.draw(backBtn);
        
        g2.setFont(new Font("Arial", Font.BOLD, 14));
        g2.drawString("BACK", backBtn.x + 40, backBtn.y + 25);
    }
}